services:
  - name: proyecto-pokemon
    type: web
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: node src/backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://pokemon-eternal.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Content-Type, Authorization, Accept"
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
      - path: /*
        name: Access-Control-Max-Age
        value: "86400"
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/$1
    healthCheckPath: /api/status

  - name: Pokemon-Eternal
    type: web
    plan: free
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://proyecto-pokemon.onrender.com/api